QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++20

DEFINES += TARGI=$$TARGET
message( "TARGET = "$$TARGI )

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    barcodes/helpers/barcode_collision_helper.cpp \
    barcodes/registry/barcode_registry.cpp \
    barcodes/repository/barcode_repository.cpp \
    barcodes/validator/barcode_validator.cpp \
    calcmodes/dialogs/mode_name_dialog.cpp \
    calcmodes/presenter/calculation_modes_presenter.cpp \
    calculation/dialogs/formula_editor_dialog.cpp \
    calculation/dialogs/material_picker_dialog2.cpp \
    calculation/presenter/calculation_mode_detail_presenter.cpp \
    expression/ast_builder.cpp \
    expression/ast_to_expression.cpp \
    expression/formula_engine.cpp \
    expression/formula_normalizer.cpp \
    calculation/service/matrix_generator.cpp \
    calculation/service/matrix_validator.cpp \
    common/layout/layout_default_store.cpp \
    common/logger/logger_gui.cpp \
    common/settings/settings_store.cpp \
    common/snapshot/snapshot_manager.cpp \
    common/system/verbose_class_initializer.cpp \
    common/system/verbose_manager.cpp \
    common/utils/attention_blinker.cpp \
    common/utils/cursor_aware_placement.cpp \
    common/utils/geometry_helper.cpp \
    common/utils/table_formatter.cpp \
    expression/expression.cpp \
    expression/keyword.cpp \
    expression/parser.cpp \
    expression/tokenizer.cpp \
    expression/variable.cpp \
    mainwindow.cpp \
    materials/view/color_badge.cpp \
    needs/manager/material_requirements_manager.cpp \
    needs/presenter/material_requirements_presenter.cpp \
    needs/registry/need_rule_registry.cpp \
    needs/repository/need_rule_repository.cpp \
    needs/view/material_picker_dialog.cpp \
    needs/view/material_requirements_view.cpp \
    calculation/manager/calculation_mode_detail_manager.cpp \
    calcmodes/manager/calculation_modes_manager.cpp \
    calculation/registry/need_calculation_detail_registry.cpp \
    calcmodes/registry/need_calculation_registry.cpp \
    calculation/repository/need_calculation_detail_repository.cpp \
    calcmodes/repository/need_calculation_repository.cpp \
    calculation/service/need_calculator.cpp \
    calculation/view/calculation_mode_detail_view.cpp \
    calcmodes/view/calculation_modes_view.cpp \
    products/presenter/product_tree_presenter.cpp \
    products/view/product_tree_panel.cpp \
    test/calcmode/need_calculation_registry_tester.cpp \
    test/calculation/formula_engine_tester.cpp \
    test/calculation/need_calculation_detail_registry_tester.cpp \
    test/common/test_data_builder.cpp \
    test/common/test_file_helper.cpp \
    test/eventlogger/event_logger_tester.cpp \
    test/filenamehelper/filenamehelper_tests.cpp \
    test/material/material_registry_tester.cpp \
    test/need/need_rule_registry_tester.cpp \
    test/overlay/material_requirements_overlay_tester.cpp \
    test/overlay/matrix_validator_tester.cpp \
    test/overlay/overlay_presenter_tester.cpp \
    test/product/product_registry_tester.cpp \
    test/settings_manager_tester.cpp \
    ui/helpers/overlay_status_helper.cpp \
    ui/widgets/overlay_icon_widget.cpp \
    workbench/view/bom_workbench.cpp \
    colors/model/named_color.cpp \
    colors/registry/color_registry.cpp \
    colors/repository/color_repository.cpp \
    common/csv/filecontext.cpp \
    common/csv/filecontext_collector.cpp \
    common/logger/event_logger.cpp \
    common/logger/log_manager.cpp \
    common/logger/logger.cpp \
    common/registry/base/registry_base.cpp \
    common/settings/settings_manager.cpp \
    common/startup/startup_manager.cpp \
    common/startup/startup_status_manager.cpp \
    common/system/lifecycle_manager.cpp \
    common/system/window_observer.cpp \
    common/utils/filehelper.cpp \
    common/utils/filename_helper.cpp \
    common/utils/project_root_locator.cpp \
    main.cpp \
    materials/view/material_table_widget.cpp \
    materials/model/crosssectionshape.cpp \
    materials/model/material_type.cpp \
    materials/repository/material_repository.cpp \
    materials/view/material_table_manager.cpp \
    products/registry/product_registry.cpp \
    products/repository/product_repository.cpp \
    products/view/product_tree_manager.cpp \
    products/view/product_tree_view.cpp \
    test/test_manager.cpp \
    ui/adapters/log_view_adapter.cpp

HEADERS += \
    barcodes/model/barcode_record.h \
    barcodes/registry/barcode_registry.h \
    barcodes/repository/barcode_repository.h \
    barcodes/helpers/barcode_collision_helper.h \
    barcodes/validator/barcode_validator.h \
    calcmodes/dialogs/mode_name_dialog.h \
    calcmodes/presenter/calculation_modes_presenter.h \
    calcmodes/repository/need_calculation_traits.h \
    calcmodes/view/mode_row_delegate.h \
    calculation/dialogs/formula_editor_dialog.h \
    calculation/dialogs/material_picker_dialog2.h \
    calculation/presenter/calculation_mode_detail_presenter.h \
    expression/ast.h \
    expression/ast_builder.h \
    expression/ast_to_expression.h \
    expression/formula_engine.h \
    expression/formula_normalizer.h \
    calculation/service/matrix_generator.h \
    calculation/service/matrix_missing_detail.h \
    calculation/service/matrix_validator.h \
    common/layout/layout_default_store.h \
    common/logger/logger_gui.h \
    common/model/barcode_base.h \
    common/model/barcode_hierarchical_entity.h \
    common/model/barcode_identifiable_entity.h \
    common/model/entity.h \
    common/model/hierarchical_base.h \
    common/model/identifiable_entity.h \
    common/model/iregistry_entity.h \
    common/registry/barcode/barcode_index_mixin.h \
    common/registry/barcode/barcode_lookup_mixin.h \
    common/registry/barcode/id_lookup_registry_interface.h \
    common/registry/base/barcode_capable_interface.h \
    common/registry/base/registry_engine_base.h \
    common/registry/contract_checks.h \
    common/registry/core/registry_core.h \
    common/registry/feature/register_me.h \
    common/registry/hierarchy/hierarchy_mixin.h \
    common/registry/manager/registry_traits.h \
    common/registry/mixins/bulk_load_mixin.h \
    common/registry/mixins/collector_mixin.h \
    common/registry/mixins/connection_workflow_mixin.h \
    common/registry/mixins/crud_mixin.h \
    common/registry/mixins/crud_workflow_mixin.h \
    common/registry/mixins/id_lookup_mixin.h \
    common/registry/mixins/mixin_contract_checks.h \
    common/registry/mixins/test_support_mixin.h \
    common/registry/subscription_token.h \
    common/settings/settings_store.h \
    common/snapshot/snapshot_manager.h \
    common/snapshot/workbench_snapshot.h \
    common/system/nameof.hpp \
    common/registry/feature/registry_catalog.h \
    common/system/verbose_class_initializer.h \
    common/system/verbose_manager.h \
    common/utils/attention_blinker.h \
    common/utils/cursor_aware_placement.h \
    common/utils/font_utils.h \
    common/utils/geometry_helper.h \
    common/utils/optional_utils.h \
    common/utils/table_formatter.h \
    connections/connection_entity.h \
    connections/connection_importer.h \
    connections/connection_registry_engine.h \
    connections/connection_repository.h \
    expression/expression.h \
    expression/function.h \
    expression/keyword.h \
    expression/parser.h \
    expression/token.h \
    expression/tokenizer.h \
    expression/variable.h \
    materials/view/color_badge.h \
    needs/manager/material_requirements_manager.h \
    needs/model/need_rule.h \
    needs/presenter/material_requirements_presenter.h \
    needs/registry/need_rule_registry.h \
    needs/repository/need_rule_repository.h \
    needs/repository/need_rule_traits.h \
    needs/view/material_picker_dialog.h \
    needs/view/material_requirements_view.h \
    calculation/manager/calculation_mode_detail_manager.h \
    calcmodes/manager/calculation_modes_manager.h \
    calcmodes/model/need_calculation.h \
    calculation/model/need_calculation_detail.h \
    calculation/registry/need_calculation_detail_registry.h \
    calcmodes/registry/need_calculation_registry.h \
    calculation/repository/need_calculation_detail_repository.h \
    calcmodes/repository/need_calculation_repository.h \
    calculation/service/need_calculator.h \
    calculation/view/calculation_mode_detail_view.h \
    calcmodes/view/calculation_modes_view.h \
    products/presenter/product_tree_presenter.h \
    products/view/product_tree_panel.h \
    test/calcmode/need_calculation_registry_tester.h \
    test/calculation/formula_engine_tester.h \
    test/calculation/need_calculation_detail_registry_tester.h \
    test/common/test_data_builder.h \
    test/common/test_file_helper.h \
    test/common/test_module_base.h \
    test/eventlogger/event_logger_tester.h \
    test/filenamehelper/filenamehelper_tests.h \
    test/material/material_registry_tester.h \
    test/need/need_rule_registry_tester.h \
    test/overlay/material_requirements_overlay_tester.h \
    test/overlay/matrix_validator_tester.h \
    test/overlay/overlay_presenter_tester.h \
    test/product/product_registry_tester.h \
    test/settings_manager_tester.h \
    ui/helpers/overlay_status_helper.h \
    ui/helpers/repository_overlay_widget.h \
    ui/widgets/overlay_icon_widget.h \
    workbench/view/bom_workbench.h \
    colors/model/named_color.h \
    colors/registry/color_registry.h \
    colors/model/colorconstants.h \
    colors/model/ralsystem.h \
    colors/repository/color_repository.h \
    common/csv/csvhelper.h \
    common/csv/csvimporter.h \
    common/csv/filecontext_collector.h \
    common/logger/error_bucketizer.h \
    common/logger/event_logger.h \
    common/csv/filecontext.h \
    common/logger/log_manager.h \
    common/logger/logger.h \
    common/csv/rowerror.h \
    common/model/hierarchical_entity.h \
    common/registry/feature/registry_base.h \
    common/registry/manager/registry_manager.h \
    common/settings/settings_manager.h \
    common/startup/startup_manager.h \
    common/startup/startup_status.h \
    common/startup/startup_status_manager.h \
    common/system/buildnumber.h \
    common/system/lifecycle_manager.h \
    common/system/signal_helper.h \
    common/system/sysinfo_helper.h \
    common/system/window_observer.h \
    common/utils/filehelper.h \
    common/utils/filename_helper.h \
    common/utils/project_root_locator.h \
    common/utils/qt_event_util.h \
    common/utils/scoped_per_thread_lock.h \
    mainwindow.h \
    materials/view/material_table_widget.h \
    materials/model/crosssectionshape.h \
    materials/model/cutting_mode.h \
    materials/model/material_master.h \
    materials/model/material_type.h \
    materials/model/painting_mode.h \
    materials/registry/material_registry.h \
    materials/repository/material_repository.h \
    materials/view/material_table_manager.h \
    products/model/product_master.h \
    products/registry/product_registry.h \
    products/repository/product_repository.h \
    products/view/product_tree_manager.h \
    products/view/product_tree_view.h \
    test/test_manager.h \
    ui/adapters/log_view_adapter.h \
    ui/style/color_helper.h

FORMS += \
    mainwindow.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    README.md \
    docs/barcodes_module_overview.md \
    docs/entity_contract.md \
    docs/entity_matrix.md \
    docs/formula_engine_dsl.md \
    docs/overlay_ux_rules.md \
    docs/registry_contract.md \
    docs/registry_matrix.md \
    run_1_1_AllapotTabla.txt \
    run_1_2_BugList.txt \
    run_1_3_0_OsszesitettHibajegyzek_Refactor.txt \
    run_1_3_1_BarcodeRegistry_Refactor.txt \
    run_1_3_2_FeladatLista.txt \
    run_1_4_DailySync.txt \
    run_2_1_AIDevelopmentHandbook.txt \
    run_2_2_JEGYZET.txt \
    run_2_3_1_Prompt_Allapottabla.txt \
    run_2_3_2_Prompt_DailySync.txt \
    run_2_3_3_Prompt_ReleaseNotes.txt \
    run_2_3_4_Prompt_SprintReview.txt \
    run_2_3_5_Prompt_BugList.txt \
    run_2_3_6_Prompt_FileList.txt \
    run_2_5_Prompt_DeveloperManual.txt \
    run_2_6_ManualsWorkflow.txt \
    run_3_1_Manifest.txt \
    run_3_1_Prompt_ArchitectureSpec.txt \
    run_3_2_Prompt_FeatureSpec.txt \
    run_3_3_Prompt_CodeGeneration.txt \
    run_3_4_Prompt_Refactor.txt \
    run_3_5_Prompt_SnippletPatching.txt \
    run_3_6_Prompt_Hybrid.txt \
    run_4_1_Rendszerterv.txt \
    run_4_2_RendszerKomponensLista.txt \
    run_4_AnyagszuksegletSzamitas.txt \
    run_4_BOMWorkbench.txt \
    run_4_ColorRegistry.txt \
    run_4_DataModelPhilosophy.md \
    run_4_GenerikusKapcsolotabla.txt \
    run_4_LogDoc.txt \
    run_4_RegistryManager.txt \
    run_4_ThreePhaseImport.md \
    run_4_ValidationRules.txt \
    run_4_WidgetGeometrySettings.txt \
    run_4_WordcodeTranslation.txt \
    run_5_0.md \
    run_5_1.md \
    run_5_2.md \
    testdata/barcodes.csv \
    testdata/products.csv \
    testdata/needrules.csv \
    testdata/settings.ini
